Algoritmo "LacoRepeticaoPara"
// Disciplina : [Linguagem e Lógica de Programação]
// Professor : Antonio Carlos Nicolodi
// Descrição : Aqui você descreve o que o programa faz! (função)
// Autor(a) : Nome do(a) aluno(a)
// Data atual : 04/04/2022
Var
// Seção de Declarações das variáveis
contadora:inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para contadora de 0 ate 100 passo 10 faca
Escreval(contadora)
fimpara



Fimalgoritmo